/* ==========================================================================
   WIKI · SCHELETRO DEL SAPERE  (il grafo universale)
   --------------------------------------------------------------------------
   Derivato dalla gerarchia Topics di OpenAlex (licenza CC0):
   4 domini → 26 campi → 252 sottocampi. NON è scritto a mano: è generato una
   volta dai dati OpenAlex e committato come dato statico. Molti rami restano
   VUOTI ma VISIBILI nel cervello 3D — si illuminano quando un modulo scritto
   li "ingerisce" (campo `nodo` in wiki/wiki-index.js).

   Ogni nodo:  { id, label, level: "dominio"|"campo"|"sottocampo", parent }

   Caricato via <script>, non via fetch: sicuro anche aprendo da file://.
   Il cervello fonde questo scheletro con i moduli scritti — vedi
   wiki/graph/graph-model.js.

   Etichette in italiano: i 4 domini, i 26 campi e i sottocampi di Informatica
   e Matematica (i rami oggi illuminati). Gli altri sottocampi restano con il
   nome inglese di OpenAlex finché non arriva contenuto che li accende: allora
   si traducono, una riga ciascuno.

   Per rigenerarlo da capo servono le API pubbliche OpenAlex
   (/domains, /fields, /subfields). Fonte della gerarchia:
   https://help.openalex.org/hc/en-us/articles/24736129405719-Topics
   ========================================================================== */

window.WIKI_SKELETON = [
  { id: "dom-1", label: "Scienze della Vita", level: "dominio", parent: null },
  { id: "dom-2", label: "Scienze Sociali", level: "dominio", parent: null },
  { id: "dom-3", label: "Scienze Fisiche", level: "dominio", parent: null },
  { id: "dom-4", label: "Scienze della Salute", level: "dominio", parent: null },
  { id: "fld-11", label: "Scienze Agrarie e Biologiche", level: "campo", parent: "dom-1" },
  { id: "fld-12", label: "Arti e Studi Umanistici", level: "campo", parent: "dom-2" },
  { id: "fld-13", label: "Biochimica, Genetica e Biologia Molecolare", level: "campo", parent: "dom-1" },
  { id: "fld-14", label: "Economia Aziendale e Management", level: "campo", parent: "dom-2" },
  { id: "fld-15", label: "Ingegneria Chimica", level: "campo", parent: "dom-3" },
  { id: "fld-16", label: "Chimica", level: "campo", parent: "dom-3" },
  { id: "fld-17", label: "Informatica", level: "campo", parent: "dom-3" },
  { id: "fld-18", label: "Scienze delle Decisioni", level: "campo", parent: "dom-2" },
  { id: "fld-19", label: "Scienze della Terra e Planetarie", level: "campo", parent: "dom-3" },
  { id: "fld-20", label: "Economia, Econometria e Finanza", level: "campo", parent: "dom-2" },
  { id: "fld-21", label: "Energia", level: "campo", parent: "dom-3" },
  { id: "fld-22", label: "Ingegneria", level: "campo", parent: "dom-3" },
  { id: "fld-23", label: "Scienze Ambientali", level: "campo", parent: "dom-3" },
  { id: "fld-24", label: "Immunologia e Microbiologia", level: "campo", parent: "dom-1" },
  { id: "fld-25", label: "Scienza dei Materiali", level: "campo", parent: "dom-3" },
  { id: "fld-26", label: "Matematica", level: "campo", parent: "dom-3" },
  { id: "fld-27", label: "Medicina", level: "campo", parent: "dom-4" },
  { id: "fld-28", label: "Neuroscienze", level: "campo", parent: "dom-1" },
  { id: "fld-29", label: "Infermieristica", level: "campo", parent: "dom-4" },
  { id: "fld-30", label: "Farmacologia, Tossicologia e Farmaceutica", level: "campo", parent: "dom-1" },
  { id: "fld-31", label: "Fisica e Astronomia", level: "campo", parent: "dom-3" },
  { id: "fld-32", label: "Psicologia", level: "campo", parent: "dom-2" },
  { id: "fld-33", label: "Scienze Sociali", level: "campo", parent: "dom-2" },
  { id: "fld-34", label: "Veterinaria", level: "campo", parent: "dom-4" },
  { id: "fld-35", label: "Odontoiatria", level: "campo", parent: "dom-4" },
  { id: "fld-36", label: "Professioni Sanitarie", level: "campo", parent: "dom-4" },
  { id: "sub-1100", label: "General Agricultural and Biological Sciences", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1102", label: "Agronomy and Crop Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1103", label: "Animal Science and Zoology", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1104", label: "Aquatic Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1105", label: "Ecology, Evolution, Behavior and Systematics", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1106", label: "Food Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1107", label: "Forestry", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1108", label: "Horticulture", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1109", label: "Insect Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1110", label: "Plant Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1111", label: "Soil Science", level: "sottocampo", parent: "fld-11" },
  { id: "sub-1200", label: "General Arts and Humanities", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1202", label: "History", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1203", label: "Language and Linguistics", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1204", label: "Archeology", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1205", label: "Classics", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1206", label: "Conservation", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1207", label: "History and Philosophy of Science", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1208", label: "Literature and Literary Theory", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1209", label: "Museology", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1210", label: "Music", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1211", label: "Philosophy", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1212", label: "Religious studies", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1213", label: "Visual Arts and Performing Arts", level: "sottocampo", parent: "fld-12" },
  { id: "sub-1302", label: "Aging", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1303", label: "Biochemistry", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1304", label: "Biophysics", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1305", label: "Biotechnology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1306", label: "Cancer Research", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1307", label: "Cell Biology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1308", label: "Clinical Biochemistry", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1309", label: "Developmental Biology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1310", label: "Endocrinology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1311", label: "Genetics", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1312", label: "Molecular Biology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1313", label: "Molecular Medicine", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1314", label: "Physiology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1315", label: "Structural Biology", level: "sottocampo", parent: "fld-13" },
  { id: "sub-1402", label: "Accounting", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1403", label: "Business and International Management", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1404", label: "Management Information Systems", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1405", label: "Management of Technology and Innovation", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1406", label: "Marketing", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1407", label: "Organizational Behavior and Human Resource Management", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1408", label: "Strategy and Management", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1409", label: "Tourism, Leisure and Hospitality Management", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1410", label: "Industrial relations", level: "sottocampo", parent: "fld-14" },
  { id: "sub-1502", label: "Bioengineering", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1503", label: "Catalysis", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1504", label: "Chemical Health and Safety", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1506", label: "Filtration and Separation", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1507", label: "Fluid Flow and Transfer Processes", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1508", label: "Process Chemistry and Technology", level: "sottocampo", parent: "fld-15" },
  { id: "sub-1602", label: "Analytical Chemistry", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1603", label: "Electrochemistry", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1604", label: "Inorganic Chemistry", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1605", label: "Organic Chemistry", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1606", label: "Physical and Theoretical Chemistry", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1607", label: "Spectroscopy", level: "sottocampo", parent: "fld-16" },
  { id: "sub-1702", label: "Intelligenza Artificiale", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1703", label: "Teoria della Computazione", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1704", label: "Computer Grafica e CAD", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1705", label: "Reti e Comunicazioni", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1706", label: "Applicazioni Informatiche", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1707", label: "Visione Artificiale", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1708", label: "Hardware e Architetture", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1709", label: "Interazione Uomo-Macchina", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1710", label: "Sistemi Informativi", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1711", label: "Elaborazione dei Segnali", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1712", label: "Software", level: "sottocampo", parent: "fld-17" },
  { id: "sub-1800", label: "General Decision Sciences", level: "sottocampo", parent: "fld-18" },
  { id: "sub-1802", label: "Information Systems and Management", level: "sottocampo", parent: "fld-18" },
  { id: "sub-1803", label: "Management Science and Operations Research", level: "sottocampo", parent: "fld-18" },
  { id: "sub-1804", label: "Statistics, Probability and Uncertainty", level: "sottocampo", parent: "fld-18" },
  { id: "sub-1902", label: "Atmospheric Science", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1904", label: "Earth-Surface Processes", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1906", label: "Geochemistry and Petrology", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1907", label: "Geology", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1908", label: "Geophysics", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1910", label: "Oceanography", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1911", label: "Paleontology", level: "sottocampo", parent: "fld-19" },
  { id: "sub-1912", label: "Space and Planetary Science", level: "sottocampo", parent: "fld-19" },
  { id: "sub-2000", label: "General Economics, Econometrics and Finance", level: "sottocampo", parent: "fld-20" },
  { id: "sub-2002", label: "Economics and Econometrics", level: "sottocampo", parent: "fld-20" },
  { id: "sub-2003", label: "Finance", level: "sottocampo", parent: "fld-20" },
  { id: "sub-2100", label: "General Energy", level: "sottocampo", parent: "fld-21" },
  { id: "sub-2102", label: "Energy Engineering and Power Technology", level: "sottocampo", parent: "fld-21" },
  { id: "sub-2103", label: "Fuel Technology", level: "sottocampo", parent: "fld-21" },
  { id: "sub-2104", label: "Nuclear Energy and Engineering", level: "sottocampo", parent: "fld-21" },
  { id: "sub-2105", label: "Renewable Energy, Sustainability and the Environment", level: "sottocampo", parent: "fld-21" },
  { id: "sub-2200", label: "General Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2202", label: "Aerospace Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2203", label: "Automotive Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2204", label: "Biomedical Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2205", label: "Civil and Structural Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2206", label: "Computational Mechanics", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2207", label: "Control and Systems Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2208", label: "Electrical and Electronic Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2209", label: "Industrial and Manufacturing Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2210", label: "Mechanical Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2211", label: "Mechanics of Materials", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2212", label: "Ocean Engineering", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2213", label: "Safety, Risk, Reliability and Quality", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2214", label: "Media Technology", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2215", label: "Building and Construction", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2216", label: "Architecture", level: "sottocampo", parent: "fld-22" },
  { id: "sub-2302", label: "Ecological Modeling", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2303", label: "Ecology", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2304", label: "Environmental Chemistry", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2305", label: "Environmental Engineering", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2306", label: "Global and Planetary Change", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2307", label: "Health, Toxicology and Mutagenesis", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2308", label: "Management, Monitoring, Policy and Law", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2309", label: "Nature and Landscape Conservation", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2310", label: "Pollution", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2311", label: "Industrial and Manufacturing Engineering", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2312", label: "Water Science and Technology", level: "sottocampo", parent: "fld-23" },
  { id: "sub-2402", label: "Applied Microbiology and Biotechnology", level: "sottocampo", parent: "fld-24" },
  { id: "sub-2403", label: "Immunology", level: "sottocampo", parent: "fld-24" },
  { id: "sub-2404", label: "Microbiology", level: "sottocampo", parent: "fld-24" },
  { id: "sub-2405", label: "Parasitology", level: "sottocampo", parent: "fld-24" },
  { id: "sub-2406", label: "Virology", level: "sottocampo", parent: "fld-24" },
  { id: "sub-2500", label: "General Materials Science", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2502", label: "Biomaterials", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2503", label: "Ceramics and Composites", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2504", label: "Electronic, Optical and Magnetic Materials", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2505", label: "Materials Chemistry", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2506", label: "Metals and Alloys", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2507", label: "Polymers and Plastics", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2508", label: "Surfaces, Coatings and Films", level: "sottocampo", parent: "fld-25" },
  { id: "sub-2602", label: "Algebra e Teoria dei Numeri", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2604", label: "Matematica Applicata", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2605", label: "Matematica Computazionale", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2607", label: "Matematica Discreta e Combinatoria", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2608", label: "Geometria e Topologia", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2610", label: "Fisica Matematica", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2611", label: "Modellazione e Simulazione", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2612", label: "Analisi Numerica", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2613", label: "Statistica e Probabilità", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2614", label: "Informatica Teorica", level: "sottocampo", parent: "fld-26" },
  { id: "sub-2702", label: "Anatomy", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2703", label: "Anesthesiology and Pain Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2704", label: "Biochemistry", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2705", label: "Cardiology and Cardiovascular Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2706", label: "Critical Care and Intensive Care Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2707", label: "Complementary and alternative medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2708", label: "Dermatology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2711", label: "Emergency Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2712", label: "Endocrinology, Diabetes and Metabolism", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2713", label: "Epidemiology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2714", label: "Family Practice", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2715", label: "Gastroenterology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2716", label: "Genetics", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2717", label: "Geriatrics and Gerontology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2718", label: "Health Informatics", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2720", label: "Hematology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2721", label: "Hepatology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2723", label: "Immunology and Allergy", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2724", label: "Internal Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2725", label: "Infectious Diseases", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2726", label: "Microbiology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2727", label: "Nephrology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2728", label: "Neurology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2729", label: "Obstetrics and Gynecology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2730", label: "Oncology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2731", label: "Ophthalmology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2732", label: "Orthopedics and Sports Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2733", label: "Otorhinolaryngology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2734", label: "Pathology and Forensic Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2735", label: "Pediatrics, Perinatology and Child Health", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2736", label: "Pharmacology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2737", label: "Physiology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2738", label: "Psychiatry and Mental health", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2739", label: "Public Health, Environmental and Occupational Health", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2740", label: "Pulmonary and Respiratory Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2741", label: "Radiology, Nuclear Medicine and Imaging", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2742", label: "Rehabilitation", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2743", label: "Reproductive Medicine", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2745", label: "Rheumatology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2746", label: "Surgery", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2747", label: "Transplantation", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2748", label: "Urology", level: "sottocampo", parent: "fld-27" },
  { id: "sub-2802", label: "Behavioral Neuroscience", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2803", label: "Biological Psychiatry", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2804", label: "Cellular and Molecular Neuroscience", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2805", label: "Cognitive Neuroscience", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2806", label: "Developmental Neuroscience", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2807", label: "Endocrine and Autonomic Systems", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2808", label: "Neurology", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2809", label: "Sensory Systems", level: "sottocampo", parent: "fld-28" },
  { id: "sub-2910", label: "Issues, ethics and legal aspects", level: "sottocampo", parent: "fld-29" },
  { id: "sub-2911", label: "Leadership and Management", level: "sottocampo", parent: "fld-29" },
  { id: "sub-2916", label: "Nutrition and Dietetics", level: "sottocampo", parent: "fld-29" },
  { id: "sub-2922", label: "Research and Theory", level: "sottocampo", parent: "fld-29" },
  { id: "sub-3002", label: "Drug Discovery", level: "sottocampo", parent: "fld-30" },
  { id: "sub-3003", label: "Pharmaceutical Science", level: "sottocampo", parent: "fld-30" },
  { id: "sub-3004", label: "Pharmacology", level: "sottocampo", parent: "fld-30" },
  { id: "sub-3005", label: "Toxicology", level: "sottocampo", parent: "fld-30" },
  { id: "sub-3102", label: "Acoustics and Ultrasonics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3103", label: "Astronomy and Astrophysics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3104", label: "Condensed Matter Physics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3105", label: "Instrumentation", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3106", label: "Nuclear and High Energy Physics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3107", label: "Atomic and Molecular Physics, and Optics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3108", label: "Radiation", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3109", label: "Statistical and Nonlinear Physics", level: "sottocampo", parent: "fld-31" },
  { id: "sub-3200", label: "General Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3202", label: "Applied Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3203", label: "Clinical Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3204", label: "Developmental and Educational Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3205", label: "Experimental and Cognitive Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3206", label: "Neuropsychology and Physiological Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3207", label: "Social Psychology", level: "sottocampo", parent: "fld-32" },
  { id: "sub-3300", label: "General Social Sciences", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3302", label: "Archeology", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3303", label: "Development", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3304", label: "Education", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3305", label: "Geography, Planning and Development", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3306", label: "Health", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3307", label: "Human Factors and Ergonomics", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3308", label: "Law", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3309", label: "Library and Information Sciences", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3310", label: "Linguistics and Language", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3311", label: "Safety Research", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3312", label: "Sociology and Political Science", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3313", label: "Transportation", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3314", label: "Anthropology", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3315", label: "Communication", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3316", label: "Cultural Studies", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3317", label: "Demography", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3318", label: "Gender Studies", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3319", label: "Life-span and Life-course Studies", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3320", label: "Political Science and International Relations", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3321", label: "Public Administration", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3322", label: "Urban Studies", level: "sottocampo", parent: "fld-33" },
  { id: "sub-3402", label: "Equine", level: "sottocampo", parent: "fld-34" },
  { id: "sub-3404", label: "Small Animals", level: "sottocampo", parent: "fld-34" },
  { id: "sub-3500", label: "General Dentistry", level: "sottocampo", parent: "fld-35" },
  { id: "sub-3504", label: "Oral Surgery", level: "sottocampo", parent: "fld-35" },
  { id: "sub-3505", label: "Orthodontics", level: "sottocampo", parent: "fld-35" },
  { id: "sub-3506", label: "Periodontics", level: "sottocampo", parent: "fld-35" },
  { id: "sub-3600", label: "General Health Professions", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3603", label: "Complementary and Manual Therapy", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3604", label: "Emergency Medical Services", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3605", label: "Health Information Management", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3607", label: "Medical Laboratory Technology", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3608", label: "Medical Terminology", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3609", label: "Occupational Therapy", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3611", label: "Pharmacy", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3612", label: "Physical Therapy, Sports Therapy and Rehabilitation", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3614", label: "Radiological and Ultrasound Technology", level: "sottocampo", parent: "fld-36" },
  { id: "sub-3616", label: "Speech and Hearing", level: "sottocampo", parent: "fld-36" },
];
